# Generated by Django 2.2.3 on 2020-02-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_page_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
    ]
